#!/usr/bin/env bash
# Generate apple-client/Config/Generated.xcconfig from the repo-root .env.
#
# FWAServerConfig.h's FWA_GRPC_HOST / FWA_GRPC_TOKEN are plain C preprocessor
# `#define`s (see that header), so the way to drive them without hand-editing
# source is an Xcode build setting: GCC_PREPROCESSOR_DEFINITIONS. This script
# turns .env's GRPC_HOST / INTERNAL_GRPC_TOKEN into exactly that, via an
# .xcconfig file that Xcode/xcodebuild can pick up as a target's base
# configuration.
#
# Generated.xcconfig is git-ignored (see .gitignore) — it is build output,
# derived from your local, git-ignored .env, and must never be committed
# (it can contain a real gRPC token). This generator script IS committed.
#
# Usage:
#   1. Copy .env.example to .env at the repo root and fill in real values
#      (at minimum GRPC_HOST; INTERNAL_GRPC_TOKEN is optional).
#   2. Run: ./apple-client/Config/generate-xcconfig.sh
#   3. (Re-)run: ruby apple-client/generate_project.rb
#      generate_project.rb checks for this file and, when present, sets it
#      as FunWithActivityCore's base configuration file automatically — so
#      no manual Xcode build-settings step is needed. If you regenerate the
#      project BEFORE running this script (e.g. on a fresh clone), just
#      re-run generate_project.rb after — it's idempotent.
#
#   Manual-Xcode-UI alternative (only if you ever hand-edit the .xcodeproj
#   instead of regenerating it): select the FunWithActivityCore target →
#   Build Settings → set "Based on Configuration File" for both Debug and
#   Release to apple-client/Config/Generated.xcconfig.
#
# Without a .env / without running this script, FWAServerConfig.h's
# in-source defaults (safe placeholders) are used, and the app falls back to
# the localhost:50051 placeholder — never a real address.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
OUT_FILE="${SCRIPT_DIR}/Generated.xcconfig"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "==> No .env found at ${ENV_FILE} — copy .env.example to .env and fill in real values first." >&2
  exit 1
fi

GRPC_HOST=""
INTERNAL_GRPC_TOKEN=""
while IFS='=' read -r key value; do
  [[ -z "${key}" || "${key}" == \#* ]] && continue
  case "${key}" in
    GRPC_HOST) GRPC_HOST="${value}" ;;
    INTERNAL_GRPC_TOKEN) INTERNAL_GRPC_TOKEN="${value}" ;;
  esac
done < <(grep -v '^\s*#' "${ENV_FILE}" | grep -v '^\s*$')

if [[ -z "${GRPC_HOST}" ]]; then
  echo "==> GRPC_HOST is not set in ${ENV_FILE} — nothing to generate." >&2
  exit 1
fi

{
  echo "// Generated by apple-client/Config/generate-xcconfig.sh from ${ENV_FILE}."
  echo "// Do not edit by hand — re-run the generator instead. Not committed."
  echo "FWA_ENV_GRPC_HOST = ${GRPC_HOST}"
  if [[ -n "${INTERNAL_GRPC_TOKEN}" ]]; then
    echo "FWA_ENV_GRPC_TOKEN = ${INTERNAL_GRPC_TOKEN}"
    echo 'GCC_PREPROCESSOR_DEFINITIONS = $(inherited) FWA_GRPC_HOST=\"$(FWA_ENV_GRPC_HOST)\" FWA_GRPC_TOKEN=\"$(FWA_ENV_GRPC_TOKEN)\"'
  else
    echo 'GCC_PREPROCESSOR_DEFINITIONS = $(inherited) FWA_GRPC_HOST=\"$(FWA_ENV_GRPC_HOST)\"'
  fi
} > "${OUT_FILE}"

echo "==> Wrote ${OUT_FILE}"
echo "==> FWA_GRPC_HOST will build to: ${GRPC_HOST}"
